//! Immutable triangle-cell seeds; camera-facing shape, fade and animation run
//! on the GPU. Generated draws retain the source face's PVS and inline model.
use super::{DrawBatch, FlattenedScene, GpuVertex, ViewerMaterial};
use sjk_shader::{ShaderCatalog, ShaderStage, SpriteFacing, SpriteKind, SurfaceSprites};
use std::error::Error;

#[path = "surface_sprite_random.rs"]
mod random;
use random::RANDOM;

const PREFIX: &str = "@sjk-surface-sprites/";
const MAX_SEEDS: usize = 262_144;

pub(crate) fn source(key: &str) -> Option<(&str, usize)> {
    let (stage, name) = key.strip_prefix(PREFIX)?.split_once('/')?;
    Some((name, stage.parse().ok()?))
}

pub(crate) fn stage(shaders: &ShaderCatalog, key: &str) -> Option<ShaderStage> {
    let (name, index) = source(key)?;
    let mut stage = shaders.get(name)?.stages.get(index)?.clone();
    stage.surface_sprites.as_ref()?;
    // QuickSprite uses the generated byte colour, not the source face's rgbGen.
    stage.rgb_generator = Some("vertex".into());
    stage.alpha_generator = Some("vertex".into());
    // QuickSprite uses fixed quad UVs, not the source mesh's tcGen/tcMods.
    stage.texture_generator = sjk_shader::TextureGenerator::Base;
    stage.texture_modifications.clear();
    Some(stage)
}

pub(crate) fn append(
    scene: &mut FlattenedScene,
    shaders: &ShaderCatalog,
) -> Result<(), Box<dyn Error>> {
    let source_draws = scene.draws.len();
    let mut variants = std::collections::HashMap::new();
    let mut total = 0;
    let mut limited = false;
    for draw_index in 0..source_draws {
        let draw = &scene.draws[draw_index];
        let material_index = draw.material;
        let key = &scene.materials[material_index].shader;
        let Some(definition) = shaders.get(key) else {
            continue;
        };
        for (stage_index, stage) in definition.stages.iter().enumerate() {
            let Some(sprite) = &stage.surface_sprites else {
                continue;
            };
            let variant = *variants
                .entry((material_index, stage_index))
                .or_insert_with(|| {
                    let index = scene.materials.len();
                    let key = &scene.materials[material_index].shader;
                    let name = format!("{PREFIX}{stage_index}/{key}");
                    scene.materials.push(ViewerMaterial {
                        shader: name,
                        lightmap: -3,
                    });
                    index
                });
            let source_range = scene.draws[draw_index].indices.clone();
            let start = u32::try_from(scene.indices.len())?;
            for offset in (source_range.start..source_range.end).step_by(3) {
                if total >= MAX_SEEDS {
                    limited = true;
                    break;
                }
                let triangle = std::array::from_fn(|i| {
                    scene.vertices[scene.indices[offset as usize + i] as usize]
                });
                cells(triangle, sprite, |cell| {
                    if total >= MAX_SEEDS {
                        limited = true;
                        return Ok(false);
                    }
                    total += 1;
                    let base = u32::try_from(scene.vertices.len())?;
                    let mut vertices = [triangle[0], triangle[1], triangle[2], triangle[0]];
                    for (i, vertex) in vertices.iter_mut().enumerate() {
                        vertex.texture_coordinates = [[1., 1.], [1., 0.], [0., 0.], [0., 1.]][i];
                    }
                    vertices[3].normal =
                        [cell.step, f32::from(cell.seed), f32::from(cell.interval)];
                    vertices[3].lightmap_coordinates = cell.cell;
                    vertices[3].color[0] = if sprite.kind == SpriteKind::Effect {
                        cell.ordinal as f32
                    } else {
                        f32::from(cell.right)
                    };
                    scene.vertices.extend(vertices);
                    scene
                        .indices
                        .extend([base, base + 1, base + 2, base, base + 2, base + 3]);
                    Ok(true)
                })?;
            }
            let draw = &scene.draws[draw_index];
            let generated = DrawBatch {
                indices: start..u32::try_from(scene.indices.len())?,
                material: variant,
                clusters: draw.clusters.clone(),
                surface_index: draw.surface_index,
                world_surface: draw.world_surface,
                hidden: draw.hidden,
                overlay: draw.overlay,
                bounds: draw.bounds,
            };
            scene.draws.push(generated);
        }
    }
    if total > 0 {
        crate::log::progress(format_args!("surface sprites: {total} immutable GPU seeds"));
    }
    if limited {
        crate::log::progress(format_args!(
            "surface sprites: decoration capped at {MAX_SEEDS} seeds; \
             map geometry remains available"
        ));
    }
    Ok(())
}

#[derive(Clone, Copy, Debug)]
struct Cell {
    cell: [f32; 2],
    step: f32,
    seed: u8,
    interval: u8,
    right: u8,
    ordinal: u32,
}

fn byte(v: f32) -> u8 {
    (v as i32) as u8
}
fn rsqrt(v: f32) -> f32 {
    let y = f32::from_bits(0x5f3759df - (v.to_bits() >> 1));
    y * (1.5 - (v * 0.5 * y * y))
}

fn cells(
    triangle: [GpuVertex; 3],
    sprite: &SurfaceSprites,
    mut emit: impl FnMut(Cell) -> Result<bool, Box<dyn Error>>,
) -> Result<(), Box<dyn Error>> {
    let vertical = matches!(sprite.kind, SpriteKind::Vertical | SpriteKind::Flattened);
    if triangle.iter().any(|v| {
        if vertical && sprite.facing != SpriteFacing::Normal {
            v.normal[2] > -0.5
        } else {
            v.normal[2]
                < if !vertical && sprite.facing != SpriteFacing::Normal {
                    0.99
                } else {
                    0.5
                }
        }
    }) {
        return Ok(());
    }
    let [a, b, c] = triangle.map(|v| v.position);
    let area = ((c[0] - a[0]) * (b[1] - a[1]) - (c[1] - a[1]) * (b[0] - a[0])).abs();
    if area <= 1.0 {
        return Ok(());
    }
    let step = sprite.density * rsqrt(area);
    // Bound malformed shaders before entering potentially unbounded float loops.
    if !step.is_finite() || step <= 0. {
        return Ok(());
    }
    let step = step.max(0.001);
    let mut seed = byte(a[0] + a[1] + b[0] + b[1] + c[0] + c[1]);
    let interval = byte(a[0] + b[1] + c[2]) | 3;
    let mut right = 0;
    let mut ordinal = 0;
    let mut i = 0.0;
    while i < 1.0 {
        let mut j = 0.0;
        while j < 1.0 - i {
            let start_seed = seed;
            let mut valid = true;
            if sprite.kind == SpriteKind::Effect {
                seed = seed.wrapping_add(interval);
            } else {
                let fa = i + RANDOM[seed as usize] * step;
                seed = seed.wrapping_add(interval);
                if !vertical && fa > 1.0 {
                    valid = false;
                } else {
                    let fb = j + RANDOM[seed as usize] * step;
                    seed = seed.wrapping_add(interval);
                    if vertical {
                        right = (right + 1) & 3;
                    }
                    valid = fa <= 1.0 && fb <= 1.0 - fa;
                    if valid {
                        seed =
                            seed.wrapping_add(interval.wrapping_mul(if vertical { 1 } else { 2 }));
                    }
                }
            }
            if valid
                && !emit(Cell {
                    cell: [i, j],
                    step,
                    seed: start_seed,
                    interval,
                    right,
                    ordinal,
                })?
            {
                return Ok(());
            }
            ordinal += 1;
            j += step;
        }
        i += step;
    }
    Ok(())
}

pub(crate) fn compile(gpu: &mut crate::world_stage::GpuStage, stage: &ShaderStage) {
    let Some(s) = &stage.surface_sprites else {
        return;
    };
    gpu.sprites = [
        [
            match s.kind {
                SpriteKind::Vertical => 1.,
                SpriteKind::Oriented => 2.,
                SpriteKind::Effect => 3.,
                SpriteKind::Flattened => 4.,
            },
            s.width,
            s.height,
            s.density,
        ],
        [s.fade_distance, s.fade_max, s.fade_scale, s.wind],
        [
            s.variance[0],
            s.variance[1],
            s.vertical_skew,
            match s.facing {
                SpriteFacing::Normal => 0.,
                SpriteFacing::Down => 1.,
                SpriteFacing::Any => 2.,
                SpriteFacing::Up => 3.,
            },
        ],
        [
            s.wind_idle,
            s.effect_duration,
            s.effect_grow[0],
            s.effect_grow[1],
        ],
        [
            s.effect_alpha[0],
            s.effect_alpha[1],
            f32::from(s.weather),
            f32::from(stage.blend == sjk_shader::StageBlend::Add),
        ],
    ];
}
