//! JA+ server commands the console completes while on a JA+ server, from the list
//! EternalJK registers for completion (`gcmds[]`, `cg_consolecmds.c:3105-3304`).
//! The server runs them and checks every admin right; they keep their real names
//! so binds made for other clients still work.

use sjk_mod::{Command, command};

pub(crate) const JA_PLUS: &[Command] = &[
    command("amlogin", "JA+: log in as admin: amlogin <password>"),
    command("amlogout", "JA+: log out as admin"),
    command("aminfo", "JA+: list the commands you may use"),
    command("amstatus", "JA+: player list"),
    command("amwhois", "JA+: players and their admin logins"),
    command("ammotd", "JA+: show the message of the day"),
    command(
        "amshowmotd",
        "JA+ admin: show the message of the day to a player",
    ),
    command("amsay", "JA+ admin: say something as admin"),
    command(
        "ampsay",
        "JA+ admin: print a message in the middle of the screen",
    ),
    command("amtele", "JA+ admin: teleport: amtele [player] [x y z yaw]"),
    command(
        "amtelemark",
        "JA+ admin: set the amtele mark where you stand",
    ),
    command("amkick", "JA+ admin: kick a player"),
    command("amban", "JA+ admin: ban a player"),
    command("amslap", "JA+ admin: slap a player"),
    command("amsleep", "JA+ admin: put a player to sleep"),
    command("amwake", "JA+ admin: wake a sleeping player"),
    command("amsilence", "JA+ admin: stop a player chatting"),
    command("amempower", "JA+ admin: give a player every Force power"),
    command("ammerc", "JA+ admin: give a player every weapon"),
    command("amprotect", "JA+ admin: protect a player from damage"),
    command("amrename", "JA+ admin: rename a player"),
    command("ammindtrick", "JA+ admin: mind-trick a player"),
    command("amghost", "JA+ admin: ghost a player"),
    command("amfreeze", "JA+ admin: freeze a player"),
    command(
        "amforcealtdim",
        "JA+ admin: put a player in the alternate dimension",
    ),
    command(
        "amunforcealtdim",
        "JA+ admin: bring a player back from the alternate dimension",
    ),
    command("amaltdim", "JA+: alternate dimension"),
    command("ammap", "JA+ admin: change the map"),
    command("amlistmaps", "JA+: list the server's maps"),
    command("amweather", "JA+ admin: change the weather"),
    command("amvstr", "JA+ admin: run a server vstr"),
    command("ampoll", "JA+ admin: start a poll"),
    command("amkillvote", "JA+ admin: end the current vote"),
    command("amdenyvote", "JA+ admin: deny a vote"),
    command("amforceteam", "JA+ admin: move a player to a team"),
    command("amlockteam", "JA+ admin: lock a team"),
    command("amgrantadmin", "JA+ admin: grant admin rights to a player"),
    command("amlookup", "JA+ admin: look up a player"),
    command("origin", "JA+: print your position"),
    command("ignore", "JA+: ignore a player"),
    command(
        "engage_fullforceduel",
        "JA+: challenge to a full Force duel",
    ),
    command("engage_gunduel", "JA+: challenge to a gun duel"),
    command("clansay", "JA+: say something to your clan"),
    command("clanpass", "JA+: set your clan password"),
    command("clanjoin", "JA+: join a clan"),
    command("clancreate", "JA+: create a clan"),
    command("clanadmin", "JA+: clan admin commands"),
    command("claninvite", "JA+: invite a player to your clan"),
    command("clanleave", "JA+: leave your clan"),
    command("clanlist", "JA+: list the clans"),
    command("claninfo", "JA+: show a clan"),
    command("clanwhois", "JA+: list the clan members on the server"),
    command("ambeg", "JA+ emote: beg"),
    command("ambeg2", "JA+ emote: beg (2)"),
    command("ambreakdance", "JA+ emote: breakdance"),
    command("ambreakdance2", "JA+ emote: breakdance (2)"),
    command("ambreakdance3", "JA+ emote: breakdance (3)"),
    command("ambreakdance4", "JA+ emote: breakdance (4)"),
    command("amcheer", "JA+ emote: cheer"),
    command("amcower", "JA+ emote: cower"),
    command("amdance", "JA+ emote: dance"),
    command("amhug", "JA+ emote: hug"),
    command("amnoisy", "JA+ emote: noisy"),
    command("ampoint", "JA+ emote: point"),
    command("amrage", "JA+ emote: rage"),
    command("amsit", "JA+ emote: sit"),
    command("amsit2", "JA+ emote: sit (2)"),
    command("amsit3", "JA+ emote: sit (3)"),
    command("amsit4", "JA+ emote: sit (4)"),
    command("amsit5", "JA+ emote: sit (5)"),
    command("amsurrender", "JA+ emote: surrender"),
    command("amsmack", "JA+ emote: smack"),
    command("amtaunt", "JA+ emote: taunt"),
    command("amtaunt2", "JA+ emote: taunt (2)"),
    command("amvictory", "JA+ emote: victory"),
    command("amwait", "JA+ emote: wait"),
];
