//! What a quick wheel choice can be: SJK's catalogue of actions, each a console
//! command with its name, its group in the Settings editor, when it counts as in
//! effect and its picture. A page may also hold a console command the player named
//! ([`super::pages::Slot::Custom`]).

/// When a choice counts as in effect, for the dot beside it on the ring.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) enum State {
    /// Never marked.
    None,
    /// The cvar holds this integer.
    Equals(&'static str, i64),
    /// The cvar is on (nonzero).
    On(&'static str),
    /// The cvar is within a hundredth of this number.
    Near(&'static str, f64),
    /// Illuminate's holocron is lit (the client's own state, no cvar holds it).
    Illuminate,
}

/// The wheel's icons, generated by Sol in the style of Jedi Academy's neutral Force
/// icons and cut by `scripts/wheel_icons.py` from two boards (the first sixteen
/// from the first, the rest, named by the actions they are for, from the
/// second); uploaded into the UI atlas at start (`ui_renderer::wheel_icon`).
pub(crate) const ICONS: [(&str, &[u8]); 45] = [
    ("drizzle", include_bytes!("../../assets/wheel/drizzle.png")),
    ("rain", include_bytes!("../../assets/wheel/rain.png")),
    ("storm", include_bytes!("../../assets/wheel/storm.png")),
    ("snow", include_bytes!("../../assets/wheel/snow.png")),
    (
        "ground_fog",
        include_bytes!("../../assets/wheel/ground_fog.png"),
    ),
    ("clouds", include_bytes!("../../assets/wheel/clouds.png")),
    (
        "maps_own",
        include_bytes!("../../assets/wheel/maps_own.png"),
    ),
    (
        "weather_off",
        include_bytes!("../../assets/wheel/weather_off.png"),
    ),
    (
        "third_person",
        include_bytes!("../../assets/wheel/third_person.png"),
    ),
    (
        "nameplates",
        include_bytes!("../../assets/wheel/nameplates.png"),
    ),
    (
        "screenshot",
        include_bytes!("../../assets/wheel/screenshot.png"),
    ),
    ("hud", include_bytes!("../../assets/wheel/hud.png")),
    ("afk", include_bytes!("../../assets/wheel/afk.png")),
    (
        "cosmetics",
        include_bytes!("../../assets/wheel/cosmetics.png"),
    ),
    ("sun", include_bytes!("../../assets/wheel/sun.png")),
    ("moon", include_bytes!("../../assets/wheel/moon.png")),
    // The second board, row by row.
    (
        "game_menu",
        include_bytes!("../../assets/wheel/game_menu.png"),
    ),
    (
        "first_setup",
        include_bytes!("../../assets/wheel/first_setup.png"),
    ),
    (
        "free_camera",
        include_bytes!("../../assets/wheel/free_camera.png"),
    ),
    ("timer", include_bytes!("../../assets/wheel/timer.png")),
    ("fps", include_bytes!("../../assets/wheel/fps.png")),
    (
        "speedometer",
        include_bytes!("../../assets/wheel/speedometer.png"),
    ),
    (
        "lagometer",
        include_bytes!("../../assets/wheel/lagometer.png"),
    ),
    ("console", include_bytes!("../../assets/wheel/console.png")),
    (
        "whats_new",
        include_bytes!("../../assets/wheel/whats_new.png"),
    ),
    (
        "team_menu",
        include_bytes!("../../assets/wheel/team_menu.png"),
    ),
    (
        "spectate",
        include_bytes!("../../assets/wheel/spectate.png"),
    ),
    ("respawn", include_bytes!("../../assets/wheel/respawn.png")),
    ("inspect", include_bytes!("../../assets/wheel/inspect.png")),
    ("duel", include_bytes!("../../assets/wheel/duel.png")),
    (
        "saber_style",
        include_bytes!("../../assets/wheel/saber_style.png"),
    ),
    (
        "saber_toggle",
        include_bytes!("../../assets/wheel/saber_toggle.png"),
    ),
    ("taunt", include_bytes!("../../assets/wheel/taunt.png")),
    ("bow", include_bytes!("../../assets/wheel/bow.png")),
    (
        "meditate",
        include_bytes!("../../assets/wheel/meditate.png"),
    ),
    (
        "flourish",
        include_bytes!("../../assets/wheel/flourish.png"),
    ),
    ("gloat", include_bytes!("../../assets/wheel/gloat.png")),
    (
        "vote_yes",
        include_bytes!("../../assets/wheel/vote_yes.png"),
    ),
    ("vote_no", include_bytes!("../../assets/wheel/vote_no.png")),
    ("record", include_bytes!("../../assets/wheel/record.png")),
    (
        "stop_record",
        include_bytes!("../../assets/wheel/stop_record.png"),
    ),
    (
        "reconnect",
        include_bytes!("../../assets/wheel/reconnect.png"),
    ),
    // Illuminate's own picture, the holocron the Force bar shows for it (bundled
    // with the client, not cut from a board).
    (
        "illuminate",
        include_bytes!("../../assets/holocron/force_illuminate.png"),
    ),
    ("custom", include_bytes!("../../assets/wheel/custom.png")),
    (
        "quick_wheel",
        include_bytes!("../../assets/wheel/quick_wheel.png"),
    ),
];

/// The picture of every custom console command ([`super::pages::Slot::Custom`]).
pub(crate) const CUSTOM_ICON: &str = "custom";
/// The wheel's own picture, a ring of discs: Settings' Quick wheel category
/// wears it (`settings_icons::texture` finds it).
pub(crate) const WHEEL_ICON: &str = "quick_wheel";

/// Index of icon `name` in [`ICONS`].
pub(crate) fn icon_index(name: &str) -> Option<usize> {
    ICONS.iter().position(|(icon, _)| *icon == name)
}

/// The Settings editor's groups of actions, in the order it lists them.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) enum Group {
    Camera,
    Interface,
    Player,
    Emotes,
    Toys,
    Weather,
    Time,
    Server,
}

impl Group {
    pub(crate) const ALL: [Self; 8] = [
        Self::Camera,
        Self::Interface,
        Self::Player,
        Self::Emotes,
        Self::Toys,
        Self::Weather,
        Self::Time,
        Self::Server,
    ];

    /// The group's sub-heading.
    pub(crate) fn label(self) -> &'static str {
        match self {
            Self::Camera => "Camera",
            Self::Interface => "Interface",
            Self::Player => "Player",
            Self::Emotes => "Emotes",
            Self::Toys => "Toys",
            Self::Weather => "Weather",
            Self::Time => "Time of day",
            Self::Server => "Votes, demos and server",
        }
    }
}

/// One action a wheel choice can run.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct Action {
    /// How `wheel.json` names it; never changes once released.
    pub(crate) id: &'static str,
    /// Its name on the ring, in sentence case.
    pub(crate) label: &'static str,
    /// The console command it runs, exactly as typing it would.
    pub(crate) command: &'static str,
    pub(crate) group: Group,
    pub(crate) state: State,
    /// Its picture in [`ICONS`]; without one the ring shows its name on a disc.
    pub(crate) icon: Option<&'static str>,
}

const fn action(
    id: &'static str,
    label: &'static str,
    command: &'static str,
    group: Group,
    state: State,
    icon: Option<&'static str>,
) -> Action {
    Action {
        id,
        label,
        command,
        group,
        state,
        icon,
    }
}

use Group::*;

/// Every action, grouped in the editor's order. The first sixteen are the two
/// pages the wheel started with (`general` and `weather`).
pub(crate) const ACTIONS: &[Action] = &[
    action(
        "third_person",
        "Third person",
        "togglecamera",
        Camera,
        State::None,
        Some("third_person"),
    ),
    action(
        "nameplates",
        "Nameplates",
        "nameplates",
        Interface,
        State::On("cg_nameplate"),
        Some("nameplates"),
    ),
    action(
        "hud",
        "HUD on/off",
        "toggle cg_drawHud",
        Interface,
        State::On("cg_drawHud"),
        Some("hud"),
    ),
    action(
        "screenshot",
        "Screenshot",
        "screenshotJPEG",
        Interface,
        State::None,
        Some("screenshot"),
    ),
    action(
        "cosmetics",
        "Cosmetics",
        "cosmetics",
        Player,
        State::None,
        Some("cosmetics"),
    ),
    action("afk", "AFK", "afk", Player, State::None, Some("afk")),
    action(
        "game_menu",
        "Game menu",
        "togglemenu",
        Interface,
        State::None,
        Some("game_menu"),
    ),
    action(
        "first_setup",
        "First setup",
        "firstsetup",
        Interface,
        State::None,
        Some("first_setup"),
    ),
    action(
        "weather_map",
        "Map's weather",
        "r_weatherForce 0",
        Weather,
        State::Equals("r_weatherForce", 0),
        Some("maps_own"),
    ),
    action(
        "drizzle",
        "Drizzle",
        "r_weatherForce 1",
        Weather,
        State::Equals("r_weatherForce", 1),
        Some("drizzle"),
    ),
    action(
        "rain",
        "Rain",
        "r_weatherForce 2",
        Weather,
        State::Equals("r_weatherForce", 2),
        Some("rain"),
    ),
    action(
        "storm",
        "Storm",
        "r_weatherForce 3",
        Weather,
        State::Equals("r_weatherForce", 3),
        Some("storm"),
    ),
    action(
        "snow",
        "Snow",
        "r_weatherForce 4",
        Weather,
        State::Equals("r_weatherForce", 4),
        Some("snow"),
    ),
    action(
        "ground_fog",
        "Ground fog",
        "toggle r_weatherFog 1 2",
        Weather,
        State::Equals("r_weatherFog", 2),
        Some("ground_fog"),
    ),
    action(
        "clouds",
        "Clouds",
        "toggle r_clouds",
        Weather,
        State::On("r_clouds"),
        Some("clouds"),
    ),
    action(
        "weather_toggle",
        "Weather on/off",
        "toggle r_weather",
        Weather,
        State::On("r_weather"),
        Some("weather_off"),
    ),
    // Beyond the first two pages.
    action(
        "free_camera",
        "Free camera",
        "freecam",
        Camera,
        State::None,
        Some("free_camera"),
    ),
    action(
        "camera_control",
        "Camera control",
        "cameracontrol",
        Camera,
        State::None,
        Some("free_camera"),
    ),
    action(
        "timer",
        "Match timer",
        "toggle cg_drawTimer",
        Interface,
        State::On("cg_drawTimer"),
        Some("timer"),
    ),
    action(
        "fps",
        "FPS counter",
        "toggle cg_drawFps",
        Interface,
        State::On("cg_drawFps"),
        Some("fps"),
    ),
    action(
        "speedometer",
        "Speedometer",
        "toggle cg_speedometer",
        Interface,
        State::On("cg_speedometer"),
        Some("speedometer"),
    ),
    action(
        "lagometer",
        "Lagometer",
        "toggle cg_lagometer",
        Interface,
        State::On("cg_lagometer"),
        Some("lagometer"),
    ),
    action(
        "console",
        "Console",
        "toggleconsole",
        Interface,
        State::None,
        Some("console"),
    ),
    action(
        "whats_new",
        "What's new",
        "changelog",
        Interface,
        State::None,
        Some("whats_new"),
    ),
    action(
        "team_menu",
        "Team menu",
        "teammenu",
        Player,
        State::None,
        Some("team_menu"),
    ),
    action(
        "spectate",
        "Spectate",
        "team spectator",
        Player,
        State::None,
        Some("spectate"),
    ),
    action(
        "respawn",
        "Respawn",
        "kill",
        Player,
        State::None,
        Some("respawn"),
    ),
    action(
        "inspect",
        "Inspect player",
        "inspect",
        Player,
        State::None,
        Some("inspect"),
    ),
    action(
        "duel",
        "Engage duel",
        "engage_duel",
        Player,
        State::None,
        Some("duel"),
    ),
    action(
        "saber_style",
        "Saber style",
        "saberAttackCycle",
        Player,
        State::None,
        Some("saber_style"),
    ),
    action(
        "saber_toggle",
        "Saber on/off",
        "sv_saberswitch",
        Player,
        State::None,
        Some("saber_toggle"),
    ),
    action(
        "taunt",
        "Taunt",
        "taunt",
        Emotes,
        State::None,
        Some("taunt"),
    ),
    action("bow", "Bow", "bow", Emotes, State::None, Some("bow")),
    action(
        "meditate",
        "Meditate",
        "meditate",
        Emotes,
        State::None,
        Some("meditate"),
    ),
    action(
        "flourish",
        "Flourish",
        "flourish",
        Emotes,
        State::None,
        Some("flourish"),
    ),
    action(
        "gloat",
        "Gloat",
        "gloat",
        Emotes,
        State::None,
        Some("gloat"),
    ),
    // SJK's toys, one entry each: the Toys page's choices.
    action(
        "illuminate",
        "Illuminate",
        "force_illuminate",
        Toys,
        State::Illuminate,
        Some("illuminate"),
    ),
    action(
        "day",
        "Day",
        "r_dayHour 12",
        Time,
        State::Near("r_dayHour", 12.0),
        Some("sun"),
    ),
    action(
        "night",
        "Night",
        "r_dayHour 0",
        Time,
        State::Near("r_dayHour", 0.0),
        Some("moon"),
    ),
    action(
        "vote_yes",
        "Vote yes",
        "vote yes",
        Server,
        State::None,
        Some("vote_yes"),
    ),
    action(
        "vote_no",
        "Vote no",
        "vote no",
        Server,
        State::None,
        Some("vote_no"),
    ),
    action(
        "record",
        "Record demo",
        "record",
        Server,
        State::None,
        Some("record"),
    ),
    action(
        "stop_record",
        "Stop recording",
        "stoprecord",
        Server,
        State::None,
        Some("stop_record"),
    ),
    action(
        "reconnect",
        "Reconnect",
        "reconnect",
        Server,
        State::None,
        Some("reconnect"),
    ),
];

/// Index in [`ACTIONS`] of the action `wheel.json` names `id`.
pub(crate) fn action_index(id: &str) -> Option<usize> {
    ACTIONS
        .iter()
        .position(|action| action.id.eq_ignore_ascii_case(id.trim()))
}

/// The ids of the actions the wheel's first pages had, in their order.
pub(crate) const GENERAL: [&str; 8] = [
    "third_person",
    "nameplates",
    "hud",
    "screenshot",
    "cosmetics",
    "afk",
    "game_menu",
    "first_setup",
];
/// The ids of the Toys page's default choices.
pub(crate) const TOYS: [&str; 1] = ["illuminate"];
pub(crate) const WEATHER: [&str; 8] = [
    "weather_map",
    "drizzle",
    "rain",
    "storm",
    "snow",
    "ground_fog",
    "clouds",
    "weather_toggle",
];

#[cfg(test)]
mod tests {
    use super::*;

    /// Longest action name, in characters: the ring's middle shows it whole.
    const LABEL_CHARS: usize = 16;

    #[test]
    fn every_action_is_named_once_and_its_picture_exists() {
        for (index, action) in ACTIONS.iter().enumerate() {
            assert_eq!(action_index(action.id), Some(index), "{}", action.id);
            assert!(action.label.chars().count() <= LABEL_CHARS, "{}", action.id);
            assert!(action.label.is_ascii() && action.command.is_ascii());
            assert!(!action.command.trim().is_empty());
            if let Some(icon) = action.icon {
                assert!(icon_index(icon).is_some(), "{icon}");
            }
        }
        for id in GENERAL.iter().chain(&WEATHER).chain(&TOYS) {
            assert!(action_index(id).is_some(), "{id}");
        }
        // Every group has something to offer, in the editor's order.
        for group in Group::ALL {
            assert!(
                ACTIONS.iter().any(|action| action.group == group),
                "{group:?}"
            );
        }
        assert_eq!(action_index(" Rain "), Some(10));
        assert_eq!(action_index("hail"), None);
    }

    #[test]
    fn every_icon_is_a_cell_sized_picture() {
        for (name, bytes) in ICONS {
            let icon = image::load_from_memory(bytes).expect(name).into_rgba8();
            assert_eq!(icon.dimensions(), (128, 128), "{name}");
            // Transparent corners: cut out of the board, not a square.
            assert_eq!(icon.get_pixel(0, 0)[3], 0, "{name}");
        }
        assert!(ICONS.len() <= crate::ui_renderer::WHEEL_ICON_CELLS);
        // Every picture is used: by an action, a custom command or Settings.
        for (name, _) in ICONS {
            assert!(
                ACTIONS.iter().any(|action| action.icon == Some(name))
                    || [CUSTOM_ICON, WHEEL_ICON].contains(&name),
                "{name}"
            );
        }
        // Every action has its picture, and every picture its own name.
        for action in ACTIONS {
            assert!(action.icon.is_some(), "{}", action.id);
        }
        for (index, (name, _)) in ICONS.iter().enumerate() {
            assert_eq!(icon_index(name), Some(index), "{name} twice");
        }
        assert!(icon_index(CUSTOM_ICON).is_some() && icon_index(WHEEL_ICON).is_some());
    }
}
