"""Write the credits page's history: everyone's features, pull requests and commits.

    python scripts/credits_history.py            rewrite the file from main's history
    python scripts/credits_history.py --check    fail when the file is out of date

The credits page (crates/sjk-viewer/src/credits.rs) folds each person's work under
their card. This script reads it from git and writes it to
crates/sjk-viewer/assets/credits_history.txt, which the client builds in. Run it in
every merge into main, after the merge commit exists (docs/sjk.md "Credits").

Every commit belongs to the merge that brought it in: walking the merges oldest
first, a merge takes the commits of its second parent that no earlier merge took, so
a pull request merged into JKR and then into SJK counts once. Each merge is one piece
of work: a `personal/<topic>` merge is a feature titled by its message, a pull request
merge (SJK or JKR) carries its number and its title on GitHub, and merges of the same
pull request (review rounds) are one piece. Commits made straight on main are a piece
each. A piece belongs to the pull request's author on GitHub, else to whoever made
most of its commits; commits by Claude count for the piece's owner. GitHub is asked
through `gh`; without it the titles come from the merge messages.

Everyone who has work must be in PEOPLE and have a card in credits.txt (the tests
check the second).
"""

import argparse, collections, json, re, subprocess, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "crates" / "sjk-viewer" / "assets" / "credits_history.txt"
SJK_REPO = "Sol-Vulpes/SJK"
JKR_REPO = "Bishop-R/JKR"

# Git author names and GitHub logins -> the card's name in credits.txt. None: the
# commit counts for the owner of the piece it is part of.
PEOPLE = {
    "Sol-Vulpes": "Sol",
    "Bishop-R": "Bishop",
    "Creyon94": "Creyon",
    "lumaya": "lumaya",
    "lumayaa": "lumaya",
    "Claude": None,
}
# The person a piece made only of Claude's commits belongs to.
DEFAULT_OWNER = "Sol"

HEADER = """\
# Everyone's work for the credits page, newest first. Generated by
# scripts/credits_history.py from git and GitHub: do not edit by hand, run the
# script in the merge instead (docs/sjk.md "Credits").
#
#   = Name                      A person, as named by a card in credits.txt.
#   + dd/mm/yyyy | ref | title  A feature or pull request (ref "SJK #2", "JKR #48",
#                               or "-"), dated by its merge into main.
#   - hash | by | subject       One of its commits, oldest first; "by" names who
#                               made it when that is not the piece's owner.
"""

ASCII = {"×": "x", "—": "-", "–": "-", "’": "'", "‘": "'",
         "“": '"', "”": '"', "·": "-", "…": "...", "→": "->",
         "é": "e", "è": "e", "à": "a", "°": " deg", "µ": "u",
         "≤": "<=", "≥": ">=", " ": " "}


def ascii_text(text):
    text = "".join(ASCII.get(c, c) for c in text)
    return "".join(c if 32 <= ord(c) < 127 else "?" for c in text).strip()


def git(*args):
    return subprocess.run(["git", "-C", str(ROOT), *args], capture_output=True, text=True,
                          encoding="utf-8", check=True).stdout


def pull_requests(repo):
    """{number: (title, login)} of `repo`'s pull requests, or {} without gh."""
    try:
        out = subprocess.run(
            ["gh", "pr", "list", "--repo", repo, "--state", "all", "--limit", "1000",
             "--json", "number,title,author"],
            capture_output=True, text=True, encoding="utf-8", check=True).stdout
    except (OSError, subprocess.CalledProcessError) as error:
        print(f"warning: no pull requests from {repo} ({error}); titles from merge messages",
              file=sys.stderr)
        return {}
    return {pr["number"]: (pr["title"], (pr.get("author") or {}).get("login", ""))
            for pr in json.loads(out)}


def person(name):
    if name not in PEOPLE:
        sys.exit(f"credits_history: {name!r} has work but is not in PEOPLE; add them there "
                 "and give them a card in crates/sjk-viewer/assets/credits.txt")
    return PEOPLE[name]


def date(iso):
    year, month, day = iso.split("-")
    return f"{day}/{month}/{year}"


# Merge messages naming a pull request: the pattern (its number in group "n") and the
# repository, None for "Merge PR #N (title)", whose title tells.
PR_PATTERNS = [
    (re.compile(r"^Merge pull request #(?P<n>\d+) from "), "JKR"),
    (re.compile(r"^Merge SJK pull request #(?P<n>\d+) "), "SJK"),
    (re.compile(r"^Merge JKR #(?P<n>\d+) \("), "JKR"),
    (re.compile(r"^Merge \S+(?: round \d+)? \(PR #(?P<n>\d+)"), "JKR"),
    (re.compile(r"^Merge PR #(?P<n>\d+) \((?P<title>.*)\) into "), None),
]
# "Merge personal/topic (description) into main", the description optional.
TOPIC = re.compile(r"^Merge (\S+)(?: round \d+)?(?: \((.*)\))? into (\S+)$")


def classify(subject, jkr_prs):
    """(repo, number) of the pull request a merge message names, or None."""
    for pattern, repo in PR_PATTERNS:
        match = pattern.match(subject)
        if not match:
            continue
        number = int(match.group("n"))
        if repo is None:
            # SJK's numbering, unless JKR has a pull request of that number and title.
            jkr_title = jkr_prs.get(number, ("",))[0]
            repo = "JKR" if jkr_title == match.group("title") else "SJK"
        return repo, number
    return None


class Piece:
    def __init__(self, key, title, ref):
        self.key, self.title, self.ref = key, title, ref
        self.commits = []      # (iso date, hash, author, subject)
        self.merge_sha = None  # the newest merge (or commit) that brought it
        self.login = None      # GitHub author of the pull request

    def owner(self):
        if self.login:
            return person(self.login) or DEFAULT_OWNER
        counts = collections.Counter(person(c[2]) for c in self.commits)
        counts.pop(None, None)
        return counts.most_common(1)[0][0] if counts else DEFAULT_OWNER


def landing_days():
    """{sha: iso date} of the day each commit (merges too) reached main."""
    days = {}
    for line in git("rev-list", "--first-parent", "--reverse", "--format=%H %P%x09%cs",
                    "HEAD").splitlines():
        if line.startswith("commit "):
            continue
        shas, day = line.split("\t")
        sha, *parents = shas.split()
        if len(parents) > 1:
            for brought in git("rev-list", f"{parents[0]}..{sha}").split():
                days.setdefault(brought, day)
        days.setdefault(sha, day)
    return days


def build():
    sjk_prs, jkr_prs = pull_requests(SJK_REPO), pull_requests(JKR_REPO)
    commits = {}
    for line in git("log", "--no-merges", "--format=%H%x09%an%x09%as%x09%s").splitlines():
        sha, author, day, subject = line.split("\t", 3)
        commits[sha] = (day, sha, author, subject)
    direct = [sha for sha in git("rev-list", "--first-parent", "--no-merges", "HEAD").split()]

    pieces = {}
    taken = set(direct)

    def single(sha, merge):
        """A piece of one commit, titled by it."""
        piece = pieces.setdefault(sha, Piece(sha, commits[sha][3], "-"))
        piece.commits = [commits[sha]]
        piece.merge_sha = merge

    for line in git("log", "--merges", "--reverse", "--topo-order",
                    "--format=%H%x09%P%x09%s").splitlines():
        sha, parents, subject = line.split("\t", 2)
        first, second = parents.split()[:2]
        brought = [c for c in git("rev-list", "--no-merges", "--reverse", "--topo-order",
                                  f"{first}..{second}").split() if c not in taken]
        taken.update(brought)
        pr = classify(subject, jkr_prs)
        topic = TOPIC.match(subject)
        if pr:
            repo, number = pr
            title, login = (sjk_prs if repo == "SJK" else jkr_prs).get(number, (None, None))
            if title is None:
                inner = re.search(r"\((.*)\)", subject)
                title = inner.group(1) if inner and not inner.group(1).startswith("PR #") else None
            piece = pieces.setdefault(pr, Piece(pr, title, f"{repo} #{number}"))
            piece.login = piece.login or login
        elif topic and "/" in topic.group(1) and topic.group(3).endswith("main") \
                and not topic.group(1).startswith("upstream/"):
            branch, description, _ = topic.groups()
            key = (branch, description)
            piece = pieces.setdefault(key, Piece(key, description, "-"))
        else:
            # Upstream syncs and main merged into a topic: what is left of them is
            # commits made straight on a main branch, a piece each.
            for c in brought:
                single(c, sha)
            continue
        piece.commits.extend(commits[c] for c in brought)
        piece.merge_sha = sha
    for sha in direct:
        single(sha, sha)

    days = landing_days()
    times = dict(line.split() for line in git("log", "--format=%H %ct").splitlines())
    people = collections.defaultdict(list)
    for piece in pieces.values():
        if not piece.commits:
            continue
        piece.landed = days.get(piece.merge_sha) or max(c[0] for c in piece.commits)
        piece.time = int(times.get(piece.merge_sha, 0))
        if piece.title is None:
            piece.title = piece.commits[0][3]
        people[piece.owner()].append(piece)
    return people


def sentence(title):
    """`title` with a capital, unless its first word is a name (cl_x, ^0, sjk/x)."""
    word = title.split(" ", 1)[0].rstrip(":;,")
    return title[0].upper() + title[1:] if word.isalpha() and word.islower() else title


def render(people):
    order = sorted(people, key=lambda name: (name != "Sol", name != "Bishop", name.lower()))
    out = [HEADER]
    for name in order:
        out.append(f"\n= {name}\n")
        pieces = sorted(people[name], reverse=True, key=lambda p: (p.landed, p.time))
        for piece in pieces:
            title = sentence(ascii_text(piece.title))
            out.append(f"+ {date(piece.landed)} | {piece.ref} | {title}\n")
            for _, sha, author, subject in piece.commits:
                by = person(author) or name
                out.append(f"- {sha[:7]} | {'' if by == name else by} | {ascii_text(subject)}\n")
    return "".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="fail when the file differs from what the history gives")
    args = parser.parse_args()
    people = build()
    text = render(people)
    if args.check:
        # A Windows checkout may have turned the file's line ends into CRLF.
        current = OUTPUT.read_bytes().decode("ascii").replace("\r\n", "\n") \
            if OUTPUT.exists() else ""
        if current != text:
            sys.exit(f"{OUTPUT.relative_to(ROOT)} is out of date: run scripts/credits_history.py")
        return
    OUTPUT.write_text(text, encoding="ascii", newline="\n")
    for name, pieces in people.items():
        print(f"{name}: {len(pieces)} pieces, {sum(len(p.commits) for p in pieces)} commits")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()

