"""Cut the settings menu's icons out of Sol's settings icon board.

The board (Game_UI_icon_design_board_2K, 2752x1536, generated by Sol) holds four
rows of eight grey metal discs on a dark ground, in the style of the quick wheels'
icons. Each disc is cut out as wheel_icons.py cuts the wheels' (a circle a little
inside its rim, anti-aliased, scaled to the UI atlas cell, 128x128).

    python scripts/settings_icons.py board.jpg crates/sjk-viewer/assets/settings

Needs Pillow, numpy and scipy (pip install pillow numpy scipy).
"""

import sys
from pathlib import Path

from PIL import Image

from wheel_icons import cut, discs

# The board's rows, left to right.
NAMES = [
    "settings", "key_bindings", "options", "first_setup", "graphics", "sound", "gameplay", "network",
    "movement", "interaction", "weapons", "force_powers", "mouse_joystick", "other_controls", "game_options", "interface",
    "hud", "scoreboard", "video", "image", "lighting", "shadows", "weather", "text",
    "camera", "crosshair", "nameplates", "identity", "changelog", "credits", "update", "import",
]


def main():
    board, out = Path(sys.argv[1]), Path(sys.argv[2])
    out.mkdir(parents=True, exist_ok=True)
    image = Image.open(board).convert("RGB")
    for name, (x, y, radius) in zip(NAMES, discs(image, len(NAMES), lower_half=False)):
        cut(image, x, y, radius).save(out / f"{name}.png", optimize=True)
        print(f"{name}: centre ({x:.0f}, {y:.0f}), radius {radius:.0f}")


if __name__ == "__main__":
    main()
