"""Cut the quick wheels' icons out of Sol's icon board.

The board (Game_HUD_icon_design_board_2K, 2752x1536, generated by Sol) holds four
rows of eight icons on a dark ground; the last two rows are grey metal discs in
the style of Jedi Academy's neutral Force icons, which the quick wheels use. Each
disc is found as a bright blob on the dark ground, cut out on a circle a little
inside its rim (so no ground shows at the edge), anti-aliased, and scaled to the
UI atlas cell (128x128).

    python scripts/wheel_icons.py board.jpg crates/sjk-viewer/assets/wheel

Needs Pillow, numpy and scipy (pip install pillow numpy scipy).
"""

import sys
from pathlib import Path

import numpy as np
from PIL import Image
from scipy import ndimage

# Row 3 then row 4 of the board, left to right.
NAMES = [
    "drizzle", "rain", "storm", "snow", "ground_fog", "clouds", "maps_own", "weather_off",
    "third_person", "nameplates", "screenshot", "hud", "afk", "cosmetics", "sun", "moon",
]
SIZE = 128
# How far inside the found rim the cut runs, in board pixels.
INSET = 3.0


def discs(image, count=len(NAMES), lower_half=True):
    """The grey discs: bright blobs (in the lower half only, by default), sorted by
    row and column. Returns (centre_x, centre_y, radius) in board pixels."""
    luma = np.asarray(image.convert("L"), dtype=np.float32)
    height = luma.shape[0]
    mask = luma > 70
    if lower_half:
        mask[: height // 2] = False
    mask = ndimage.binary_closing(mask, iterations=4)
    mask = ndimage.binary_fill_holes(mask)
    labels, count = ndimage.label(mask)
    found = []
    for index, box in enumerate(ndimage.find_objects(labels), start=1):
        rows, columns = box
        h, w = rows.stop - rows.start, columns.stop - columns.start
        # A disc is about as wide as tall and large; spokes or text are not.
        if min(h, w) < 120 or abs(h - w) > 0.15 * max(h, w):
            continue
        found.append(((columns.start + columns.stop) / 2, (rows.start + rows.stop) / 2, max(h, w) / 2))
    if len(found) != count:
        raise SystemExit(f"expected {count} discs, found {len(found)}")
    found.sort(key=lambda disc: (round(disc[1] / 100), disc[0]))
    return found


def cut(image, centre_x, centre_y, radius):
    """One disc on transparency, SIZE square."""
    half = int(np.ceil(radius)) + 2
    box = (int(centre_x) - half, int(centre_y) - half, int(centre_x) + half, int(centre_y) + half)
    crop = np.asarray(image.crop(box).convert("RGBA"), dtype=np.float32)
    ys, xs = np.mgrid[0 : crop.shape[0], 0 : crop.shape[1]]
    distance = np.hypot(xs + box[0] + 0.5 - centre_x, ys + box[1] + 0.5 - centre_y)
    # A one-pixel ramp at the rim: smooth once scaled down.
    alpha = np.clip(radius - INSET - distance + 0.5, 0.0, 1.0)
    crop[..., 3] = alpha * 255.0
    picture = Image.fromarray(crop.astype(np.uint8), "RGBA")
    return picture.resize((SIZE, SIZE), Image.LANCZOS)


def main():
    board, out = Path(sys.argv[1]), Path(sys.argv[2])
    out.mkdir(parents=True, exist_ok=True)
    image = Image.open(board).convert("RGB")
    for name, (x, y, radius) in zip(NAMES, discs(image)):
        cut(image, x, y, radius).save(out / f"{name}.png", optimize=True)
        print(f"{name}: centre ({x:.0f}, {y:.0f}), radius {radius:.0f}")


if __name__ == "__main__":
    main()
